#! /bin/bash
brew install stow
mkdir -p ~/.emacs.d/
touch ~/.emacs.d/.keep

for i in $(ls -d */);
do
  stow -v -t ~/ -R ${i%%/};
done
mkdir -p ~/.mail/{gmail,fastmail,riseup}

brew install asdf atuin

curl -L https://get.oh-my.fish | fish 
omf install bass
brew install asdf
asdf plugin  add python
asdf install python latest
pip install -U flake8 jedi autopep8 yapf importmagic
npm i -g eslint stylelint tern
cargo install racer
cargo install rustfmt
cargo install ripgrep
cargo install cargo-outdated
cargo install cargo-profiler
cargo install cargo-update
cargo install diesel_cli

