#! /bin/bash
mkdir -p ~/.emacs.d/
touch ~/.emacs.d/.keep

for i in $(ls -d */);
do
  stow -v -t ~/ -R ${i%%/};
done
mkdir -p ~/.mail/{gmail,work,riseup}

echo "
Please remember to install the following packages:

  msmtp
  isync
  mu
  terminal-notifier
  cask

Installing requirements...
"
pip install -U flake8 jedi autopep8 yapf importmagic
npm i -g eslint stylelint tern
cargo install racer --force
cargo install rustfmt --force
