#! /bin/bash
mkdir -p ~/.emacs.d/
touch ~/.emacs.d/.keep

for i in $(ls -d */);
do
  stow -v -t ~/ -R ${i%%/};
done
mkdir -p ~/.mail/{gmail,work,riseup}
ln -s `pwd`/.eslintrc ~/.eslintrc

echo "
Please remember to install the following packages:

  msmtp
  isync
  keyring (pip)
  mu
  terminal-notifier
  cask

"
